name: insight
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jinja2=3.1.6
  - pip=25.0
  - python=3.11
  - pyyaml=6.0
  - r-base=4.4.2
  - r-dplyr=1.1.4
  - r-ggplot2=3.5.1
  - r-gtable=0.3.6
  - r-purrr=1.0.4
  - r-ragg=1.3.3
  - r-readr=2.1.5
  - r-scales=1.3.0
  - r-tidyr
  - yaml=0.2.5
  - duckdb==1.2.1
  - networkx==3.4.2
  - numpy==1.24.4
  - pandas==2.2.3
  - pysam==0.22.1
  - scipy==1.15.2
  - requests
  - pip:
    - git+https://github.com/douymLab/INSIGHT.git